### ISSUE TITLE
Uncaught Error: Class 'thewulf7\travelPayouts\Travel' not found in ....

### ISSUE THREAD

**Issue by rapgithub** [thewulf7/travel-payouts#18]
I have installed via terminal everything as indicated

composer require thewulf7/travel-payouts

and then in php I use this where my_token it is my real token

this is my index.php

use thewulf7\travelPayouts\Travel; 
$travel = new Travel('my_token');

but I got all the time this error below:

Uncaught Error: Class 'thewulf7\travelPayouts\Travel' not found in .... etc...
Error: Class 'thewulf7\travelPayouts\Travel' not found

I have installed already via composer all this below:

composer/installers      v1.2.0  A multi-framework Composer library installer
guzzle/guzzle            v3.9.3  PHP HTTP client. This library is deprecate...
guzzlehttp/guzzle        6.2.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises      v1.3.1  Guzzle promises library
guzzlehttp/psr7          1.4.2   PSR-7 message implementation that also pro...
league/oauth2-client     2.2.0   OAuth 2.0 Client Library
paragonie/random_compat  v2.0.10 PHP 5.x polyfill for random_bytes() and ra...
psr/http-message         1.0.1   Common interface for HTTP messages
ptcong/easyrequest       1.0.6   A light weight PHP http client implements ...
ramsey/array_column      1.1.3   Provides functionality for array_column() ...
symfony/event-dispatcher v2.8.19 Symfony EventDispatcher Component
thewulf7/travel-payouts  v1.1.5  PHP SDK for travelpayouts.com

the error is when doing this line

new Travel('my_token');

class not found!!!

is here a way I can test if thewulf7 travelPayouts was properly installed by composer? do I need an autoloader.php? or why namespace is not working to include the class?

use thewulf7\travelPayouts\Travel; 

any solutions?

I have installed many times this PHP SDK and same problem all the time...

what I am doing wrong?
thanks
r.

**Comment by thewulf7** [comment]
@rapgithub you need to include autoload as in all composer projects

**Comment by rapgithub** [comment]
I will check the autoload file if it is there and see what happens now... thanks

**Comment by rapgithub** [comment]
I have added the autoload.php manually because it is not included after installing everything with composer, I used this: 

require_once __DIR__ . '/vendor/autoload.php';

where vendor directory it is in the same folder now of my php files... inside its folder vendor/thewulf7/...
 
and I have got this error now:

 Fatal error: Uncaught RuntimeException: 403: in /vendor/thewulf7/travel-payouts/src/thewulf7/travelPayouts/components/Client.php on line 87

if the problem comes from this way I load the autoload.php 
I will be grateful if you tell me how can I load autoload.php in the composer the right way for this PHP SDK to work... 

thanks
I am attaching my composer installed packages as an image here... 

<img width="563" alt="screen shot 2017-04-13 at 10 19 05" src="https://cloud.githubusercontent.com/assets/11996194/24996321/af5fc3ce-2032-11e7-88c3-fe8f99390249.png">

my composer.json file in my php directory shows this inside:


{
    "name": "thewulf7/travel-payouts",
    "description": "PHP SDK for travelpayouts.com",
    "license": "MIT",
    "authors": [
        {
            "name": "Johnny Utkin",
            "email": "thewulf7@me.com"
        }
    ],
    "minimum-stability": "dev",
    "require": {
        "php": ">=5.4.0",
        "guzzle/guzzle": "*",
        "guzzlehttp/guzzle":"*",
        "ramsey/array_column": "*"
    },
    "require-dev": {
        "phpunit/phpunit": "3.7.*",
        "phpunit/php-invoker" : ">=1.1.0@stable"
    },
    "autoload": {
        "psr-0": {
            "thewulf7\\travelPayouts": "src/"
        }
    }
}

**Comment by thewulf7** [comment]
@rapgithub it's correct to include autoload like this.

Exception now is that server returns 403 on your request. Can you show me the code?

**Comment by rapgithub** [comment]
My php api_test.php on localhost now testing...

include ('vendor/autoload.php');
use thewulf7\travelPayouts\Travel; 
$travel = new Travel('api_key');

$flightService = $travel->getFlightService();
$flightService
       ->setIp('1.34.216.69')
       ->setHost('myhostname.com')
       ->setMarker('122179')
       ->addPassenger('adults', 2)
       ->addSegment('LED', 'MOW', '2017-08-01');
 $searchData = $flightService->search('ru', 'Y');
$searchResults = $flightService->getSearchResults($searchData['search_id']);

I get this error on screen:

Fatal error: Uncaught RuntimeException: 403: in /Applications/MAMP/htdocs/SDKPHP/vendor/thewulf7/travel-payouts/src/thewulf7/travelPayouts/components/Client.php:87 Stack trace: #0 /Applications/MAMP/htdocs/SDKPHP/vendor/thewulf7/travel-payouts/src/thewulf7/travelPayouts/services/FlightService.php(75): thewulf7\travelPayouts\components\Client->execute('/v1/flight_sear...', Array, 'POST', false) #1 /Applications/MAMP/htdocs/SDKPHP/api.php(39): thewulf7\travelPayouts\services\FlightService->search('ru', 'Y') #2 {main} thrown in /Applications/MAMP/htdocs/SDKPHP/vendor/thewulf7/travel-payouts/src/thewulf7/travelPayouts/components/Client.php on line 87

the line 87 in Client.php says:

            throw new \RuntimeException("{$statusCode}:{$strBody['message']}");


Also if I use

$tickets = $ticketService->getLatestPrices('LED', 'MOW', false, 'en', 'year', 1, 10);

same problem:

Fatal error: Uncaught RuntimeException: 404:Unknown endpoint. Please see documentation at http://api.travelpayouts.com/ in /Applications/MAMP/htdocs/SDKPHP/vendor/thewulf7/travel-payouts/src/thewulf7/travelPayouts/components/Client.php:87 Stack trace: #0 /Applications/MAMP/htdocs/SDKPHP/vendor/thewulf7/travel-payouts/src/thewulf7/travelPayouts/services/TicketsService.php(91): thewulf7\travelPayouts\components\Client->execute('/v1/prices/late...', Array) #1 /Applications/MAMP/htdocs/SDKPHP/api.php(42): thewulf7\travelPayouts\services\TicketsService->getLatestPrices('LED', 'MOW', false, 'rub', 'year', 1, 10) #2 {main} thrown in /Applications/MAMP/htdocs/SDKPHP/vendor/thewulf7/travel-payouts/src/thewulf7/travelPayouts/components/Client.php on line 87


Any way to make it work without problems?
thanks


I want also to use the flight search api, not the data api... is this possible with this script?

thanks

**Comment by rapgithub** [comment]
api_key it is my real api_key number but I do not want to publish it here... just to let you know I am doing it correctly...

**Comment by thewulf7** [comment]
@rapgithub will review it today :)

**Comment by thewulf7** [comment]
@rapgithub second part is very strange - because tests are passing. Try new version.

Write me to thewulf7@gmail.com - will try to solve it :)
