### ISSUE TITLE
403 unknown error while Flight Search

### ISSUE THREAD

**Issue by Arslan1122** [thewulf7/travel-payouts#22]
Please give me a solution example

**Comment by thewulf7** [comment]
@Arslan1122 please provide your code

**Comment by Arslan1122** [comment]
$travel = new Travel('My-API-Key');

 $flightService = $travel->getFlightService();
$flightService
       ->setIp('39.55.174.166')
       ->setHost('beta.aviasales.ru')
       ->setMarker('149014')
       ->addPassenger('adults', 1)
       ->addSegment('MOW', 'LED', '2017-09-22');
$searchData    = $flightService->search('en', 'Y');




$searchResults = $flightService->getSearchResults($searchData['search_id']);

**Comment by thewulf7** [comment]
@Arslan1122 thanks to @greevex for fix

**Comment by helinaik** [comment]
i am still getting the same error. even after doing the fix mentioned.
